#ifndef _CONFIG_H
#define _CONFIG_H

#define SENSOR1_PORT GPIOA
#define SENSOR2_PORT SENSOR1_PORT

#define SENSOR_PORT SENSOR1_PORT



#define SENSOR_PIN(X) GPIO_PIN_ ## X

#define SENSOR_CHANNEL(X) ADC_CHANNEL_ ## X 


#define SENSOR1_PIN GPIO_PIN_4
#define SENSOR2_PIN GPIO_PIN_6

#define SENSOR_PIN_SET ( SENSOR1_PIN | SENSOR2_PIN)



#define SENSOR1_CHANNEL ADC_CHANNEL_4
#define SENSOR2_CHANNEL ADC_CHANNEL_6

#define SENSOR1_SAMPLING_TIME ADC_SAMPLETIME_1CYCLE_5
#define SENSOR2_SAMPLING_TIME SENSOR1_SAMPLING_TIME

#define WRITE_DATA_LEN 2

#define ADC_BUFFER_LENGTH 256

#define ADDR_PORT GPIOB

#define ADDR_PIN_7 GPIO_PIN_6
#define ADDR_PIN_6 GPIO_PIN_7
#define ADDR_PIN_5 GPIO_PIN_10
#define ADDR_PIN_4 GPIO_PIN_11
#define ADDR_PIN_3 GPIO_PIN_15
#define ADDR_PIN_2 GPIO_PIN_14
#define ADDR_PIN_1 GPIO_PIN_13
#define ADDR_PIN_0 GPIO_PIN_12

#define ADDR_PIN_COUNT 4


#define RS485_ENABLE_PORT GPIOA
#define RS485_RE_PIN GPIO_PIN_8
#define RS485_DE_PIN GPIO_PIN_11


void _Error_Handler(char *, int);

#define Error_Handler() _Error_Handler(__FILE__, __LINE__)

#endif