#ifndef _CONFIG_H
#define _CONFIG_H

#define SENSOR1_PORT GPIOA
#define SENSOR2_PORT SENSOR1_PORT

#define SENSOR_PORT SENSOR1_PORT



#define SENSOR_PIN(X) GPIO_PIN_ ## X

#define SENSOR_CHANNEL(X) ADC_CHANNEL_ ## X 


#define SENSOR1_PIN GPIO_PIN_4
#define SENSOR2_PIN GPIO_PIN_6

#define SENSOR_PIN_SET GPIO_PIN_4



#define SENSOR1_CHANNEL ADC_CHANNEL_4
#define SENSOR2_CHANNEL ADC_CHANNEL_6

#define SENSOR1_PIN SENSOR_PIN(5)
#endif